### ISSUE TITLE
Why do u choose Solr

### ISSUE THREAD

**Issue by HelloTo4x** [vu2lid/ExploreSolr#1]
Hi, i am reading your project, why do you choose Solr instead of other search engines such as Elastic search... Can u tell your purpose, the pros and cons of Solr if you know, thank u so much

**Comment by vu2lid** [comment]
Hi, I was trying to create an experimental setup for interacting with an existing Solr based system. So the selection was not based on merits of Solar (or lack of them) after comparing with something like Elastic search.
